name: .NET 6 CI
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    name: .NET 6 Application
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.401' # Check for latest at link at .NET 5 download page
      - run: dotnet publish -r win-x64 -p:PublishSingleFile=true -c Release --self-contained false
      - uses: actions/upload-artifact@v3
        with:
          name: MinimalSittingNotifier-win-64.exe
          path: bin/Release/net6.0-windows/win-x64/publish/MinimalSittingNotifier.exe