name: .NET 5 CI
on: [push]

jobs:
  build:
    runs-on: windows-latest
    name: .NET 5 Application
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.301' # Check for latest at link at .NET 5 download page
      - run: dotnet publish -r win-x64 -p:PublishSingleFile=true -c Release --self-contained false
      - uses: actions/upload-artifact@v2
        with:
          name: MinimalSittingNotifier-win-64.exe
          path: bin/Release/net5.0-windows/win-x64/publish/MinimalSittingNotifier.exe